### ISSUE TITLE
Problems with Ø letter.

### ISSUE THREAD

**Issue by mortenkols** [Colorado4Wheeler/HomeKit-Bridge#63] opened 2018-03-16 20:33 UTC
Here is the log regarding devices with Ø letters.

16. mar. 2018, 20:11:05
   HomeKit Bridge Error            Exception in plugin.serverListJSONDevices line 3096: 'ascii' codec can't encode character u'\xd8' in position 15: ordinal not in range(128)
							 CODE: name = "{0}: {1}".format(d["object"], name)

16. mar. 2018, 20:11:32
   HomeKit Bridge Error            Exception in plugin.serverListJSONDevices line 3096: 'ascii' codec can't encode character u'\xf8' in position 10: ordinal not in range(128)
							 CODE: name = "{0}: {1}".format(d["object"], name)

16. mar. 2018, 20:11:54
   HomeKit Bridge Error            Exception in plugin.serverListJSONDevices line 3096: 'ascii' codec can't encode character u'\xf8' in position 10: ordinal not in range(128)
							 CODE: name = "{0}: {1}".format(d["object"], name)

   Z-Wave                          received "Stue og kjøkken - Stikk sofa" energy total to 7.84 kWh
   Z-Wave                          received "Stue og kjøkken - Stikk sofa" power load to 19.86 W

16. mar. 2018, 20:12:14
   Z-Wave                          received "Stue og kjøkken - Stikk sofa" power load to 57.01 W

16. mar. 2018, 20:12:45
   HomeKit Bridge Error            Exception in plugin.serverListJSONDevices line 3096: 'ascii' codec can't encode character u'\xf8' in position 15: ordinal not in range(128)
							 CODE: name = "{0}: {1}".format(d["object"], name)

**Comment by Colorado4Wheeler** [comment] 2018-03-16 21:52
This might take a couple of rounds of updates to weed these all out, but this particular error is fixed for the next release.  You know how we Americans are, we code for us first and forget the the rest of the world wants to play too :).

**Comment by Colorado4Wheeler** [comment] 2018-03-16 22:14
Try the newly minted [beta 17.6](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases/tag/0.17.6).

**Comment by mortenkols** [comment] 2018-03-17 10:43
Tested the new beta. Everything seems fine when i added the devices, but it pops up error in the log after the plugin restarts.

HomeKit Bridge                  Attempting to start 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge Error            Exception in plugin.buildHKAPIDetails line 1286: 'ascii' codec can't encode character u'\xf8' in position 1: ordinal not in range(128)
							 CODE: alias = r"{}".format(r["alias"]) # Convert to raw string (will escape backslashes)

   HomeKit Bridge Error            Exception in plugin.buildHKAPIDetails line 1286: 'ascii' codec can't encode character u'\xf8' in position 6: ordinal not in range(128)
							 CODE: alias = r"{}".format(r["alias"]) # Convert to raw string (will escape backslashes)

**Comment by Colorado4Wheeler** [comment] 2018-03-17 13:16
Yea, if that's where they are breaking then they wouldn't.  The good news is that is towards the end of the processes so we may break through yet!  I'll have this fixed in a new release that I may put out in a little bit just so we can try to put this particular issue to bed.

**Comment by Colorado4Wheeler** [comment] 2018-03-17 16:09
Ok, try [Beta 18](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases/tag/0.18.0) and see what happens.  It fixes this particular error but may be the final thing preventing you from using those device names.

**Comment by mortenkols** [comment] 2018-03-17 16:12
updated and tested. it stil report error.

17. mar. 2018, 17:09:07
   HomeKit Bridge                  Attempting to stop 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been stopped
   HomeKit Bridge                  Attempting to start 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been started
   Z-Wave                          sent "Gang 1. etg - Lys" off
   HomeKit Bridge                  Attempting to stop 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been stopped
   HomeKit Bridge                  Attempting to start 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge Error            Exception in plugin.buildHKAPIDetails line 1291: 'ascii' codec can't encode character u'\xf8' in position 1: ordinal not in range(128)
							 CODE: alias = r"{}".format(u"{}".format(r["alias"])) # Convert to raw string (will escape backslashes)

   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been started

17. mar. 2018, 17:10:36
   HomeKit Bridge                  Attempting to stop 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been stopped
   HomeKit Bridge                  Attempting to start 'Bod Kjeller - HomeKit Bridge'
   HomeKit Bridge Error            Exception in plugin.buildHKAPIDetails line 1291: 'ascii' codec can't encode character u'\xf8' in position 6: ordinal not in range(128)
							 CODE: alias = r"{}".format(u"{}".format(r["alias"])) # Convert to raw string (will escape backslashes)

   HomeKit Bridge                  HomeKit server 'Bod Kjeller - HomeKit Bridge' has been started

**Comment by mortenkols** [comment] 2018-03-17 16:13
i tried to delete the devices and then add them again.

**Comment by Colorado4Wheeler** [comment] 2018-03-17 16:14
I wouldn’t expect deleting to work because the problem is in the characters themselves not getting translated.  Back to the drawing board.

**Comment by Colorado4Wheeler** [comment] 2018-03-17 20:42
The next release should work, I have got it working all the way through to HomeKit.
![img_6057](https://user-images.githubusercontent.com/20329385/37559777-53a96566-29f1-11e8-9292-f5a5bdbe90be.png)

**Comment by Colorado4Wheeler** [comment] 2018-03-17 21:03
[Beta 19](https://github.com/Colorado4Wheeler/HomeKit-Bridge/releases/tag/0.19.0) has the special characters working for me all the way through to HomeKit (as you can see from the above screenshot).

**Comment by mortenkols** [comment] 2018-03-18 07:58
it seems to work now with my devices!! thanks :)

**Comment by Colorado4Wheeler** [comment] 2018-03-18 14:38
WOOT!  Glad to hear it :).

**Closed by Colorado4Wheeler** 2018-03-18 14:38 UTC
Labels: beta testing, bug
